### PR TITLE
Adds (automatic) configuration of audio sources in OBS

### PR DESCRIPTION
**Pull request by Gordin**
Following up on #14 
It's not ready to be merged yet, saving options to the config file and automatically setting devices when Beat Saber/a song starts is still missing, but you can already configure the OBS sources from a new Menu in the OBSControl Mod settings

### CODE REVIEW

**Comment by Gordin** [comment]
It's works good enough to take a look at now. It remembers devices even when they are unplugged when Beat Saber is launched, and it will set the devices every time a song starts

**Comment by Zingabopp** [comment]
Sorry about the delay, got distracted with other projects after the update X_x

**Comment by Gordin** [comment]
No problem, I also stopped on this for now until all the other plugins work again. I'll see if this works on current Beat Saber :)

**Comment by Zingabopp** [comment]
Refactor branch builds for 1.12.2, although I haven't tested it. Also, it seems CSCore doesn't play nice building in GitHub Actions, what benefits does it give over NAudio?

**Comment by Gordin** [comment]
Oh, I was just trying dev but didn't have much luck.... I'll try the other branch then.
Well, NAudio uses CSCore internally, so I'm not sure if switching is going to help ^^ Also, the benefit was that I could get it to compile... NAudio had a couple other dependencies that I didn't want to pull in because we don't need any of them. If CSCore really doesn't work, NAudio should do the same thing. Refactoring it would be a little annoying though, all the CSCore function I'm using also exist in NAudio, but with slightly altered names >_>

**Comment by Zingabopp** [comment]
There might just be a problem with the project and Nuget packages, it also says Newtonsoft couldn't be found >.>
At least for builds using `dotnet`

**Comment by Zingabopp** [comment]
Got it to build with `dotnet` by converting to an SDK project. Still some weirdness on the CI build, but it's not CSCore's fault I'm pretty sure.

**Comment by Gordin** [comment]
FYI, I tested the refactor branch and I got it to compile, but it doesn't work in Beat Saber. It actually makes a WebSocket connection to OBS, but there is some Exception that makes all other Plugins not load. Should be in the logs, but I didn't bother with it ysterday because I just wanted to play ^^ Maybe I'll look into it again today

**Comment by Gordin** [comment]
(I tested before you changed the dotnet stuff, but I guess that wouldn't have changed anything ingame as long as it compiles?)

**Pull request merged**
